// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fzqmgntdagjnhiwekcek.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZ6cW1nbnRkYWdqbmhpd2VrY2VrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg2OTU3MDQsImV4cCI6MjA3NDI3MTcwNH0.fr20FH13J9Xh4qMrwCkDqCt2P-uBwWr9fedbrFGmwLk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});